/*!
 *  \file       ak47_Types.cpp
 *  \author     Francois Best
 *  \date       22/10/2012
 *  \license    CC-BY-SA Forty Seven Effects - 2012
 *
 * THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS 
 * OF THIS CREATIVE COMMONS PUBLIC LICENSE ("CCPL" OR "LICENSE").
 * THE WORK IS PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW. 
 * ANY USE OF THE WORK OTHER THAN AS AUTHORIZED UNDER THIS LICENSE 
 * OR COPYRIGHT LAW IS PROHIBITED.
 * 
 * BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT 
 * AND AGREE TO BE BOUND BY THE TERMS OF THIS LICENSE. 
 * TO THE EXTENT THIS LICENSE MAY BE CONSIDERED TO BE A CONTRACT, 
 * THE LICENSOR GRANTS YOU THE RIGHTS CONTAINED HERE IN CONSIDERATION 
 * OF YOUR ACCEPTANCE OF SUCH TERMS AND CONDITIONS.
 * http://creativecommons.org/licenses/by-sa/3.0/
 */

#include "ak47_Types.h"

BEGIN_AK47_NAMESPACE

AVR_BEGIN_UNNAMED_NAMESPACE

void checkTypesBitWidths()
{
    AVR_STATIC_ASSERT(sizeof(float32) == 4);
    AVR_STATIC_ASSERT(sizeof(float64) == 4);
    
    AVR_STATIC_ASSERT(sizeof(int8)   == 1);
    AVR_STATIC_ASSERT(sizeof(uint8)  == 1);
    AVR_STATIC_ASSERT(sizeof(int16)  == 2);
    AVR_STATIC_ASSERT(sizeof(uint16) == 2);
    AVR_STATIC_ASSERT(sizeof(int32)  == 4);
    AVR_STATIC_ASSERT(sizeof(uint32) == 4);
    AVR_STATIC_ASSERT(sizeof(int64)  == 8);
    AVR_STATIC_ASSERT(sizeof(uint64) == 8);
    
    AVR_STATIC_ASSERT(sizeof(byte) == 1);
    
    AVR_STATIC_ASSERT(sizeof(int) == 2);
    AVR_STATIC_ASSERT(sizeof(unsigned) == 2);
}

AVR_END_UNNAMED_NAMESPACE

END_AK47_NAMESPACE
